import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootProps = {
  children: ReactNode
}

export default function RootLayout({children}: RootProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-12">{children}</div>
      </body>
    </html>
  );
}
